source 'https://rubygems.org'

gem "fastlane"
gem "cocoapods"
gem 'pry'   # For debugging ruby scripts. Comment if you don't need it.
gem 'fastlane-plugin-firebase_app_distribution'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
