fastlane_require 'pry'
fastlane_version '2.137.0'
import 'Fastfile.private'

platform :android do |options| 

  desc "Submit a new Develop Release Build to Firebase App Distribution."
  lane :distribute_develop do |options|
    distribute_to_firebase environment: :develop
  end

  desc "Submit a new Stage Release Build to Firebase App Distribution."
  lane :distribute_staging do |options|
    distribute_to_firebase environment: :staging
  end

  desc "Submit a new Production Release Build to Firebase App Distribution."
  lane :distribute_production do |options|
    distribute_to_firebase environment: :production
  end

  desc "Submit a new Production Release Build to Google Play Console."
  lane :release_production do |options|
    release_to_play_console environment: :production
  end

end
