require('colors');

const { PUSH_NOTIFICATIONS_SETUP_LINK } = require('../constants');

module.exports = function nextSteps() {
  console.log(`\n       ${'NEXT STEPS!'.bold.underline.white}       \n`);
  // Introduction message
  console.log(
    `● Your project folder has been created and it already includes the kickoff commit. ${
      `cd ${this.projectName}/`.italic
    }`.cyan
  );
  if (this.repoUrl) {
    // Remote repository initialized
    console.log(
      `● All this boilerplate has already been pushed to ${this.repoUrl}`.cyan
    );
  }
  console.log('\n\n');
  console.log(
    '● FASTLANE - fastline files was added to the project on android and iOS folders'
      .cyan
  );
  console.log(
    '  to start tu use it you need to replace some values on fastlane env files'
      .cyan
  );
  console.log('\n');
  console.log('● CONFIG - react native config was added to the project'.cyan);
  console.log(
    '  Probably you should add you API_URL and other env variables on root .env files'
      .cyan
  );
  console.log('\n');
  // Firebase
  if (this.features.hasFirebase) {
    console.log(
      '● FIREBASE - Firebase features were added to the project.'.cyan
    );
    console.log(
      '  google services files was autogenerated but you still need to replace him with the'
        .cyan
    );
    console.log(
      '  corresponding application of https://console.firebase.google.com for each environment'
        .cyan
    );
    console.log('\n');
  }
  if (this.features.pushnotifications) {
    // Push Notifications SetUp
    console.log(
      '● PUSH NOTIFICATIONS - The push notification config has been added to the project but'
        .cyan
    );
    console.log('  but you still need to manually link the ios library.'.cyan);
    console.log(
      `  Further instructions can be found here: ${PUSH_NOTIFICATIONS_SETUP_LINK.underline}`
        .cyan
    );
    console.log('\n');
  }
  if (this.features.loginandsignup) {
    // Login and SignUp next steps
    console.log(
      '● LOGIN - A basic login feature has been added. The probably next steps there are:'
        .cyan
    );
    console.log('  Add proper validations and styles to the login form'.cyan);
    console.log('  Integrate login and logout with API'.cyan);
    console.log('  style or remove Sign up'.cyan);
    console.log('\n');
  }

  if (this.features.socialloginbuttons) {
    // Social networks login buttons
    console.log(
      '● SOCIAL BUTTONS - Social buttons features have been added. \nIt includes Facebook, Google, Apple and Twitter buttons.\n\tYou need follow next steps to continue:'
        .cyan
    );
    console.log(
      '  Open the project on xcode and create a empty swift file called bridge\n\t\tand accept the bridge header autogeneration from xcode prompt.'
        .cyan
    );
    console.log(
      '  Create a file called Config.xcconfig on the root of ios project\n\t\tand add it to build configurations.'
        .cyan
    );
    console.log(
      '  Complete the Socials keys and ids (like FACEBOOK_APP_ID)\n\t\ton corresponding .env files'
        .cyan
    );
    console.log(
      '  Configure apple signing from apple member center for each\n\t\tscheme/identifier. https://github.com/invertase/react-native-apple-authentication/blob/master/docs/INITIAL_SETUP.md'
        .cyan
    );
    console.log('\n');
  }
  console.log(
    '  Finaly you can find this social buttons on components folder. All buttons have the same interface.'
      .cyan
  );
  console.log('\n\n');
};
